### ISSUE TITLE
Unit test failure

### ISSUE THREAD

**Issue by kasun** [carltongibson/neapolitan#22]
Unit tests are failing for me (3/7) in main branch. Django version `4.2.2`. Python version `3.10.3`

```
django-admin test --settings=tests.settings --pythonpath=.

Found 7 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
F...FF.

----------------------------------------------------------------------
Ran 7 tests in 0.044s

FAILED (failures=3)
```

**Comment by carltongibson** [comment]
Can you provide the actual errors please.

**Comment by carltongibson** [comment]
Regression in b1290953175916780e0116d6501624f52678c04a 

```
======================================================================
FAIL: test_list_empty (tests.tests.BasicTests.test_list_empty)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/carlton/Projects/Django/neapolitan/tests/tests.py", line 56, in test_list_empty
    self.assertContains(
  File "/Users/carlton/Envs/neapolitan/lib/python3.11/site-packages/django/test/testcases.py", line 660, in assertContains
    self.assertTrue(
AssertionError: False is not true : Couldn't find '<a href="/bookmark/new/">Add a new bookmark</a>' in response
```

Need to look at why that's not the case.
